# Generated by Django 2.0.7 on 2018-07-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='nome',
        ),
    ]
