# Generated by Django 2.0.7 on 2018-07-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
        ('livro', '0002_remove_livro_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('serie', models.IntegerField(choices=[(1, '1ª'), (2, '2ª'), (3, '3ª'), (4, '4ª'), (5, '5ª'), (6, '6ª'), (7, '7ª'), (8, '8ª')], verbose_name='Série')),
                ('nivel', models.IntegerField(choices=[(1, 'Fundamental'), (2, 'Médio')], verbose_name='Nível')),
                ('tipo', models.IntegerField(choices=[(1, 'Didático'), (2, 'Paradidático')])),
                ('preco_sugerido', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço sugerido')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Escola')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.Livro')),
            ],
            options={
                'verbose_name': 'Indicação',
                'verbose_name_plural': 'Indicações',
            },
        ),
    ]
