# Generated by Django 2.0 on 2018-07-25 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_indicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'Ruim'), (1, 'Bom/Razoável'), (2, 'Ótimo')], default=1, verbose_name='Tipo')),
                ('em_venda', models.BooleanField(default=True, verbose_name='Disponível')),
                ('vendido', models.BooleanField(default=False, verbose_name='Disponível')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.Livro')),
            ],
            options={
                'verbose_name': 'Exemplar',
                'verbose_name_plural': 'Exemplares',
            },
        ),
    ]
